### ISSUE TITLE
Add version 'contains' and 'not contains' inputs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionValidator#11]
## **Description:**

Add 2 new optional inputs to the action.

One of the new inputs will fail the action if the **_version_** input **DOES** contains a particular string value.
The other new input will fail the action if the _**version**_ **DOES NOT** contain a particular string value.

---

## **Acceptance Criteria:**
- [ ] 2 new optional inputs added with the following names
    - [ ] _**fail-if-contains**_
    - [ ] _**fail-if-does-not-contain**_
- [ ] If any of the new inputs is not used, then nothing will be checked
- [ ] If any of the new inputs is provided but is empty, null, or undefined, then nothing will be checked

### Features for '_**fail-if-contains**_' Input
- [ ] The value will be used to check if it is contained within the given '_**version**_' input value
- [ ] If the '_**version**_' input value contains the string value of the value _**fail-if-contains**_ input, the action fails
- [ ] This is checked before any API calls to nuget.org
- [ ] This is checked before syntax checking is performed

### Features for '_**fail-if-does-not-contain**_' Input
- [ ] The value will be used to check if it is NOT contained within the given '_**version**_' input value
- [ ] If the '_**version**_' input value does NOT contain the string value of the value '_**fail-if-does-not-contain**_' input, the action fails
- [ ] This is checked before any API calls to nuget.org
- [ ] This is checked before syntax checking is performed

---

### Examples For '_**fail-if-contains**_' input
Example 1:
Result: Fails
``` yaml
- name: Validate Version
  uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
  with:
    nuget-package-name: "KinsonDigital.MyPackage"
    version: v1.2.3-preview.1
    check-nuget: "true"
    fail-if-nuget-version-exists: "true"
    fail-if-contains: "-preview."
```

Example 2:
Result: Passes
``` yaml
- name: Validate Version
  uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
  with:
    nuget-package-name: "KinsonDigital.MyPackage"
    version: v1.2.3-preview.1
    check-nuget: "true"
    fail-if-nuget-version-exists: "true"
    fail-if-contains: "sample-value"
```

---

### Examples For '_**fail-if-does-not-contain**_' input
Example 1:
Result: Passes
``` yaml
- name: Validate Version
  uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
  with:
    nuget-package-name: "KinsonDigital.MyPackage"
    version: v1.2.3-preview.1
    check-nuget: "true"
    fail-if-nuget-version-exists: "true"
    fail-if-does-not-contain: "-preview.1"
```

Example 2:
Result: Fails
``` yaml
- name: Validate Version
  uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
  with:
    nuget-package-name: "KinsonDigital.MyPackage"
    version: v1.2.3-preview.1
    check-nuget: "true"
    fail-if-nuget-version-exists: "true"
    fail-if-does-not-contain: "sample-value"
```
